### ISSUE TITLE
vendor以下がGit管理下になっている点

### ISSUE THREAD

**Issue by kyoya0819** [Ablaze-MIRAI/TwStory#2]
vendorや、今回は含まれてないですがnode_modulesなどをGit管理下に置くのは推奨されません。
具体的な理由があってやっている場合はその理由をご教示いただけると幸いです。

参考：[SOja](https://ja.stackoverflow.com/questions/23725/vendor%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%82%92git%E7%AE%A1%E7%90%86%E4%B8%8B%E3%81%AB%E7%BD%AE%E3%81%8B%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AF%E4%BD%95%E6%95%85)

**Comment by code-raisan** [comment]
Composerがインストールされてない端末で使用する可能性があるからです。
v1.0完成と同時にリポジトリを見やすくするために削除する予定です

**Comment by code-raisan** [comment]
「vendorや、今回は含まれてないですがnode_modulesなどをGit管理下に置くのは推奨されません。」これに関してはよく知っていますよ。今回の場合は特例です
